# Generated by Django 4.0.4 on 2022-04-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=111111111)),
                ('feature', models.BooleanField(default=False)),
            ],
        ),
    ]
